dilatate – MORTIF
dilatate Function
14 statements
Source File
private elemental function dilatate(i, b, z) result(d)
Dilatate integer of 32 bits to integer of 64 bits.
See On Spatial Orders and Location Codes, Stocco, LJ and Schrack, G, IEEE Transaction on Computers, vol 58, n 3, March 2009. The resulting integer has 64 bits; it has only b significant bits interleaved by z zeros: bb/zx0/bb-1/zx0../b1/zx0/b0; e.g. for (b=4, z=1): b3/b2/b1/b0 => b3/0/b2/0/b1/0/b0.
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: i
Input integer.
integer(kind=I2P), intent(in) :: b
Number of significant bits of 'i' (2/4/8/16/32).
integer(kind=I1P), intent(in) :: z
Number of zero 'i' (1/2).
Return Value integer(kind=I8P)
Dilated integer.
Called By
Source Code
dilatate
Source Code
  elemental function dilatate(i, b, z) result(d)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Dilatate integer of 32 bits to integer of 64 bits.
  !<
  !< See *On Spatial Orders and Location Codes*, Stocco, LJ and Schrack, G, IEEE Transaction on Computers, vol 58, n 3, March 2009.
  !< The resulting integer has 64 bits; it has only `b` significant bits interleaved by `z` zeros: `bb/zx0/bb-1/zx0../b1/zx0/b0`;
  !< e.g. for `(b=4, z=1)`: `b3/b2/b1/b0 => b3/0/b2/0/b1/0/b0`.
  !---------------------------------------------------------------------------------------------------------------------------------
  integer(I4P), intent(in) :: i !< Input integer.
  integer(I2P), intent(in) :: b !< Number of significant bits of 'i' (2/4/8/16/32).
  integer(I1P), intent(in) :: z !< Number of zero 'i' (1/2).
  integer(I8P)             :: d !< Dilated integer.
  integer(I1P)             :: l !< Counter.
  integer(I1P)             :: m !< Counter.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  l = int(log10(b*1._R4P)*log10_2_inv, I1P)
  d = int(i, I8P)
  d = iand(d, signif(l))
  do m=l, 1_I1P, -1_I1P !(5/4/3/2/1,1,-1)
    d = iand(ior(d, ishft(d, shft(m,z))), mask(m,z))
  enddo
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction dilatate
All Procedures
bctoi_I1P bctoi_I2P bctoi_I4P bctoi_I8P bcton bctor_R16P bctor_R4P bctor_R8P bit_size bit_size bit_size_chr bit_size_R16P bit_size_R4P bit_size_R8P bstr bstr_I1P bstr_I2P bstr_I4P bstr_I8P bstr_R16P bstr_R4P bstr_R8P byte_size byte_size_chr byte_size_I1P byte_size_I2P byte_size_I4P byte_size_I8P byte_size_R16P byte_size_R4P byte_size_R8P check_endian compact_real_string contract create_indexes_file create_morton_file ctoi_I1P ctoi_I2P ctoi_I4P ctoi_I8P cton ctor_R16P ctor_R4P ctor_R8P demorton2D demorton3D digit digit_I1 digit_I2 digit_I4 digit_I8 dilatate morton2D morton3D penf_init penf_print str str_a_I1P str_a_I2P str_a_I4P str_a_I8P str_a_R16P str_a_R4P str_a_R8P str_bol str_I1P str_I2P str_I4P str_I8P str_R16P str_R4P str_R8P strf_I1P strf_I2P strf_I4P strf_I8P strf_R16P strf_R4P strf_R8P strz strz_I1P strz_I2P strz_I4P strz_I8P test_16_16_16 test_morton3D
Call graph
morton2d calls dilatate
morton3d calls dilatate
test_16_16_16 calls morton3d
test_morton3d calls morton3d
mortif_test_correctness calls test_morton3d