test_morton3D – MORTIF
test_morton3D Function
13 statements
Source File
function test_morton3D(indexes, reference) result(is_test_passed)
Test morton3 encoder/decoder.
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: indexes(1:3)
Indexes.
integer(kind=int64), intent(in) :: reference
Reference morton code.
Return Value logical (1:2)
Test result.
Calls
Called By
Source Code
test_morton3D
Source Code
  function test_morton3D(indexes, reference) result(is_test_passed)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Test morton3 encoder/decoder.
  !---------------------------------------------------------------------------------------------------------------------------------
  integer(int32), intent(in) :: indexes(1:3)        !< Indexes.
  integer(int64), intent(in) :: reference           !< Reference morton code.
  logical                    :: is_test_passed(1:2) !< Test result.
  integer(int64)             :: morton              !< Morton code.
  integer(int32)             :: de_indexes(1:3)     !< Indexes computed by decoding reference.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  morton = morton3D(i=indexes(1), j=indexes(2), k=indexes(3))
  call demorton3D(code=reference, i=de_indexes(1), j=de_indexes(2), k=de_indexes(3))
  is_test_passed(1) = morton==reference
  is_test_passed(2) = all(de_indexes==indexes)
  print "(A,3(I11,1X),A,I20,A,L1)", 'Encode ', indexes,   ' => ', morton,     ', is correct? ', is_test_passed(1)
  print "(A,I20,A,3(I11,1X),A,L1)", 'Decode ', reference, ' => ', de_indexes, ', is correct? ', is_test_passed(2)
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction test_morton3D
All Procedures
contract create_indexes_file create_morton_file demorton2D demorton3D dilatate morton2D morton3D test_16_16_16 test_morton3D
Call graph
test_morton3d calls demorton3d, morton3d
demorton3d calls contract
morton3d calls dilatate
mortif_test_correctness calls test_morton3d