test_16_16_16 – MORTIF
test_16_16_16 Function
28 statements
Source File
function test_16_16_16() result(is_test_passed)
Test morton3 encoder/decoder for the matrix [(0,0,0), (1,0,0), … (15,15,15)], namely 4096 tests.
Arguments
None
Return Value logical (1:4096)
Test result.
Calls
Source Code
test_16_16_16
Source Code
  function test_16_16_16()  result(is_test_passed)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Test morton3 encoder/decoder for the matrix [(0,0,0), (1,0,0), ... (15,15,15)], namely 4096 tests.
  !---------------------------------------------------------------------------------------------------------------------------------
  logical        :: is_test_passed(1:4096)         !< Test result.
  integer(int64) :: reference_morton(1:4096)       !< Morton code references.
  integer(int32) :: reference_indexes(1:3, 1:4096) !< Indexes references.
  integer(int32) :: unit_scratch                   !< Unit of scratch file.
  integer(int64) :: morton                         !< Morton encode result.
  integer(int32) :: indexes(1:3)                   !< Indexes decoding result.
  integer(int32) :: i                              !< Counter.
  integer(int32) :: j                              !< Counter.
  integer(int32) :: t                              !< Counter.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  call create_morton_file(u=unit_scratch)
  read(unit_scratch, *)reference_morton
  close(unit=unit_scratch)
  call create_indexes_file(u=unit_scratch)
  read(unit_scratch, *)((reference_indexes(i, j), i=3,1,-1), j=1,4096)
  close(unit=unit_scratch)
  do t=1, size(reference_morton, dim=1)
    morton = morton3D(i=reference_indexes(1,t), j=reference_indexes(2,t), k=reference_indexes(3,t))
    is_test_passed(t) = morton==reference_morton(t)
    if (.not.is_test_passed(t)) then
      print '(A,I11)', 'error: encode fail for test ', t
      print '(A,I20)', 'reference Morton code= ', reference_morton(t)
      print '(A,I20)', 'encoded Morton code= ', morton
      print '(A,3I11)', 'reference indexes= ', reference_indexes(1:3, t)
      stop
    endif
  enddo
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction test_16_16_16
All Procedures
bctoi_I1P bctoi_I2P bctoi_I4P bctoi_I8P bcton bctor_R16P bctor_R4P bctor_R8P bit_size bit_size bit_size_chr bit_size_R16P bit_size_R4P bit_size_R8P bstr bstr_I1P bstr_I2P bstr_I4P bstr_I8P bstr_R16P bstr_R4P bstr_R8P byte_size byte_size_chr byte_size_I1P byte_size_I2P byte_size_I4P byte_size_I8P byte_size_R16P byte_size_R4P byte_size_R8P check_endian compact_real_string contract create_indexes_file create_morton_file ctoi_I1P ctoi_I2P ctoi_I4P ctoi_I8P cton ctor_R16P ctor_R4P ctor_R8P demorton2D demorton3D digit digit_I1 digit_I2 digit_I4 digit_I8 dilatate morton2D morton3D penf_init penf_print str str_a_I1P str_a_I2P str_a_I4P str_a_I8P str_a_R16P str_a_R4P str_a_R8P str_bol str_I1P str_I2P str_I4P str_I8P str_R16P str_R4P str_R8P strf_I1P strf_I2P strf_I4P strf_I8P strf_R16P strf_R4P strf_R8P strz strz_I1P strz_I2P strz_I4P strz_I8P test_16_16_16 test_morton3D
Call graph
test_16_16_16 calls create_indexes_file, create_morton_file, morton3d
morton3d calls dilatate